apiVersion: v1
kind: Secret
metadata:
  name: mongodb-db-credentials
type: Opaque
data:
  mongodb-passwords: |
    WbJGabxxXub2axya
  mongodb-root-password: |
    YAkPHhQwhsyL8Sdx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
data:
  dima.sh: |
    #!/bin/bash
    mongo --username root --password $MONGODB_ROOT_PASSWORD <<EOF
    use $MONGO_DIMA_DATABASE;
    db.createUser({
      user: '$MONGODB_DIMA_USERNAME',
      pwd: '$MONGODB_DIMA_PASSWORD',
      roles: [{
        role: 'readWrite',
        db: '$MONGO_DIMA_DATABASE'
      }]
    });
    db.createCollection('delete_me');
    EOF