apiVersion: v1
data:
  mongodb-metrics-password: NnduUHQ2cVJVdlR1UVdqQQ==
  mongodb-passwords: Tm5kdVVIUTJjVkpWZGxSMVVWZHFRUT09
  mongodb-replica-set-key: VG01a2RWVklVVEpqVmtwV1pHeFNNVlZXWkhGUlVUMDk=
  mongodb-root-password: VkcwMWEyUldWa2xWVkVwcVZtdHdWMXBIZUZOTlZsWlhXa2hHVWxWVU1Eaz0=
kind: Secret
metadata:
  name: mongodb-secret
  namespace: vita
type: Opaque
