version: '2.4'
services:
  mongo:
    image: mongo
    restart: always
    ports:
    - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=vita
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongo
  rabbitmq:
    image: rabbitmq:3.10-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    configs:
      - source: rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
configs:
  rabbitmq.conf:
    content: |
      consumer_timeout = 3600000