apiVersion: v1
data:
  rabbitmq-password: MjRuNG4zcXlaUHhIZDU0ZA==
  rabbitmq-erlang-cookie: TWpSdU5HNHpjWGxhVUhoSVpEVTBaQT09
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: vita
type: Opaque
